$TTL 86400

@ IN SOA dns01.company.local. admin.company.local. (
        2026072201
        3600
        1800
        604800
        86400
)

@       IN NS dns01.company.local.

30      IN PTR dns01.company.local.


$TTL 86400

@ IN SOA dns01.company.local. admin.company.local. (
        2026072201
        3600
        1800
        604800
        86400
)

@       IN NS dns01.company.local.

5       IN PTR dhcp01.company.local.
1       IN PTR gateway.company.local.
100     IN PTR admin01.company.local.
