# DHCP Server Configuration Documentation

# Domain information
option domain-name "company.local";

# DNS server
option domain-name-servers 192.168.60.30;


# Default lease time
default-lease-time 3600;

# Maximum lease time
max-lease-time 86400;


# Authoritative DHCP server
authoritative;


# Internal LAN network
subnet 192.168.50.0 netmask 255.255.255.0 {

    # DHCP address pool
    range 192.168.50.100 192.168.50.200;

    # Default gateway
    option routers 192.168.50.1;

    # DNS server
    option domain-name-servers 192.168.60.30;

    # Domain search
    option domain-name "company.local";
}
